In [42]:
import pandas as pd

# PARA PARTICIPACOES

In [43]:
path_partic ='/dados01/workspace/ufmg_2021_m04/ufmg.lgripp/participacoes-itens.csv'

COLS = [
    'id_licitacao', #0 ##
    'id_item_licitacao', #1 ##
    #'id_orgao', #2
    #'cod_orgao', #3
    #'nome_orgao', #4
    #'cod_nome_tipo_orgao', #5
    #'nome_tipo_orgao', #6
    #'nome_regiaoplanejamento', #7
#     'ano_exercicio', #8 ##
#     'mes_licitacao', #9 ##
#     'num_lote', #10 ##
# #     'nome_lote', #11
#     'num_item', #12
     'nome_item', #13
#     'vlr_unitario', #14 ##
#     'num_quant_item', #15 ##
#     'vlr_perc_desconto', #16 ##
    #'vlr_perc_taxa_adm', #17
#     'vlr_global', #18
#     #'dsc_ind_desonera_folha', #19
#     'num_cpf_cnpj_licitante', #20 ##
    #'nome_licitante', #21
    #'cod_tipo_pessoa_licitante', #22
    #'cod_ibge_municipio', #23
    #'num_cpf_cnpj_municipio', #24
    'nome_cidade', #25
    #'nome_microrregiao', #26
    #'nome_mesorregiao', #27
    #'nome_regiao_imediata', #28
    #'nome_regiao_intermediaria' #29
    'sigla_uf', #30
    #'longitude', #31
    #'latitude' #32
]


part_df = pd.read_csv(path_partic, delimiter=';', usecols=COLS)
part_df

/dados01/workspace/ufmg_2021_m04/ufmg.esilva/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3331: DtypeWarning: Columns (0,1) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,id_licitacao,id_item_licitacao,nome_item,nome_cidade,sigla_uf
0,111889,3913090,000284 SERVICOS DE MANUTENCAO DE COMPUTADORES,IRAI DE MINAS,MG
1,111846,3911900,006786 PICK UP 02 PASSAGEIROS,IRAI DE MINAS,MG
2,111846,3911901,006787 VEICULO PEQUENO PORTE 5 PASS,IRAI DE MINAS,MG
3,111852,3911940,003968 ESGUINCHO METAL,IRAI DE MINAS,MG
4,111852,3911952,"003981 FIO SOLIDO 4,00 MM",IRAI DE MINAS,MG
...,...,...,...,...,...
29866932,582068,19038527,CONTRATACAO DE EMPRESA PARA FORNECIMENTO DE MO...,SANTO ANTONIO DO AMPARO,MG
29866933,582067,19038526,SUBSTITUICAO CIR,SANTO ANTONIO DO AMPARO,MG
29866934,582068,19038527,CONTRATACAO DE EMPRESA PARA FORNECIMENTO DE MO...,SANTO ANTONIO DO AMPARO,MG
29866935,582068,19038527,CONTRATACAO DE EMPRESA PARA FORNECIMENTO DE MO...,SANTO ANTONIO DO AMPARO,MG
29866936,582068,19038527,CONTRATACAO DE EMPRESA PARA FORNECIMENTO DE MO...,SANTO ANTONIO DO AMPARO,MG

In [44]:
#Remover itens repetidos
part_df = part_df.groupby('id_item_licitacao', as_index=False).first()

In [45]:
part_df[part_df['id_item_licitacao'] == 20140796]

,id_item_licitacao,id_licitacao,nome_item,nome_cidade,sigla_uf
9856722,20140796,615528,5647 SERVICO DE TRANSPORTE,UBERLANDIA,MG

In [46]:
# # Create tuple
# vencedores['item_info'] = vencedores[['id_licitacao','id_item_licitacao', 'nome_item']].apply(tuple, axis=1)

In [47]:
part_df

,id_item_licitacao,id_licitacao,nome_item,nome_cidade,sigla_uf
0,-1,136269,MESA DE COMPUTADOR,LAMIM,MG
1,34312,953,GASOLINA COMUM - 01,ACAIACA,MG
2,34313,953,OLEO DIESEL - 02,ACAIACA,MG
3,34314,953,OLEO DIESEL - 01,ACAIACA,MG
4,34315,953,OLEO DIESEL S10 - 01,ACAIACA,MG
...,...,...,...,...,...
13326647,9775629,286792,SERVICOS DE PUBLICACAO NO DIA-,TURVOLANDIA,MG
13326648,9775630,286792,SERVICO DE PUBLICACAO NO DIA-,TURVOLANDIA,MG
13326649,9775631,286792,SERVICO DE PUBLICA EM JORNAL,TURVOLANDIA,MG
13326650,9775632,286792,SERVICO DE PUBLICACAO EM JOR-,TURVOLANDIA,MG
13326651,id_item_licitacao,id_licitacao,nome_item,nome_cidade,sigla_uf

# RANK CNPJ

In [57]:
# Rank cnpj
path = "/dados01/workspace/ufmg_2021_m04/M04_final/M04-pipeline/fraud-detection-module/output/rank_cnpjs_treated.csv"
cnpj_participations_alarm = pd.read_csv(path,delimiter=';')

In [59]:
cnpj_participations_alarm

,cnpj,participations,alarm,NÃºmero participantes
0,4.473467e+13,"[11536148.0, 11536146.0, 18842296.0, 11536147....",1.320771e+11,67131
1,7.440149e+12,"[27572389.0, 19689382.0, 19689264.0, 6127164.0...",6.606050e+10,69270
2,7.440155e+12,"[20096239.0, 15274469.0, 9501742.0, 15225363.0...",6.606050e+10,69270
3,2.525099e+13,"[127192.0, 127194.0, 127193.0, 127191.0]",5.941575e+10,4
4,2.525099e+13,"[127192.0, 127194.0, 127193.0, 127191.0]",5.941575e+10,4
...,...,...,...,...
3614,3.467189e+13,"[28523897.0, 28523896.0]",0.000000e+00,2
3615,3.767656e+13,"[28158070.0, 28158071.0, 28158073.0, 28158072.0]",0.000000e+00,4
3616,3.959878e+13,"[28158070.0, 28158071.0, 28158073.0, 28158072.0]",0.000000e+00,4
3617,4.216081e+13,[26298634.0],0.000000e+00,1
3618,5.220146e+13,[26298634.0],0.000000e+00,1

In [60]:
# Transformar coluna participations em uma lista
col_list = cnpj_participations_alarm['participations'].to_list()
 # transformar uma lista de string para uma lista de listas
b = [eval(el) for el in col_list]
# transformar lista de lista em uma unica lista
c= [item for sublist in b for item in sublist]
itens_in_participations = list(set(c))

In [61]:
itens_in_participations

[17825798.0,
 17825822.0,
 17825823.0,
 17825824.0,
 17825825.0,
 17825826.0,
 17825827.0,
 17825828.0,
 24117340.0,
 25634780.0,
 15305226.0,
 11920747.0,
 13631727.0,
 13631728.0,
 13631748.0,
 13631752.0,
 25634817.0,
 20971854.0,
 25634822.0,
 17731056.0,
 20971913.0,
 20971914.0,
 16777612.0,
 13631891.0,
 13631892.0,
 20971937.0,
 25634836.0,
 25634840.0,
 25166406.0,
 25166468.0,
 20972179.0,
 20972180.0,
 25667101.0,
 25166520.0,
 25166521.0,
 12712706.0,
 13632244.0,
 13632245.0,
 13632246.0,
 13632247.0,
 12712707.0,
 25667102.0,
 2097947.0,
 20972329.0,
 20972330.0,
 20972331.0,
 20972332.0,
 28726480.0,
 17797781.0,
 12713344.0,
 12713346.0,
 20972425.0,
 20972426.0,
 20972427.0,
 20972428.0,
 20972429.0,
 20972430.0,
 20972431.0,
 20972432.0,
 20972433.0,
 20972435.0,
 20972436.0,
 20972437.0,
 20972440.0,
 20972441.0,
 25634936.0,
 17797784.0,
 20972466.0,
 20972468.0,
 20972474.0,
 20972475.0,
 20972476.0,
 20972479.0,
 20972486.0,
 20972487.0,
 20972496.0,
 20972500.0,
 20972507.0,
 20972512.0,
 20972513.0,
 20972514.0,
 20972529.0,
 20972530.0,
 11535376.0,
 25634964.0,
 25634965.0,
 25634966.0,
 6127136.0,
 25634977.0,
 25634978.0,
 25634980.0,
 25634983.0,
 8961986.0,
 6127142.0,
 17797796.0,
 6292736.0,
 6292737.0,
 6292738.0,
 6292739.0,
 6292740.0,
 6292741.0,
 6292742.0,
 6292743.0,
 6292744.0,
 6292745.0,
 6292746.0,
 6292747.0,
 6292748.0,
 6292749.0,
 6292750.0,
 6292751.0,
 6292752.0,
 6292753.0,
 6292754.0,
 6292755.0,
 6292756.0,
 6292757.0,
 6292758.0,
 6292759.0,
 6292760.0,
 25667106.0,
 17797799.0,
 11535669.0,
 17797800.0,
 11535676.0,
 11535686.0,
 11535687.0,
 11535707.0,
 6669482.0,
 6669483.0,
 6669489.0,
 28726485.0,
 25167280.0,
 6669494.0,
 15730102.0,
 6669495.0,
 25167292.0,
 12713465.0,
 12713466.0,
 11535873.0,
 11535876.0,
 13633040.0,
 13633041.0,
 13633042.0,
 13633043.0,
 13633045.0,
 13633047.0,
 13633048.0,
 13633049.0,
 13633050.0,
 13633052.0,
 13633053.0,
 13633054.0,
 13633055.0,
 13633057.0,
 13633058.0,
 13633059.0,
 13633060.0,
 13633061.0,
 13633062.0,
 13633066.0,
 13633067.0,
 13633068.0,
 13633069.0,
 13633070.0,
 13633071.0,
 13633072.0,
 13633076.0,
 11535959.0,
 11535960.0,
 11535961.0,
 11535962.0,
 11535963.0,
 11535965.0,
 11535967.0,
 18757460.0,
 11535969.0,
 11535970.0,
 11535971.0,
 11535972.0,
 11535974.0,
 11535975.0,
 11535976.0,
 11535977.0,
 11535978.0,
 11535979.0,
 11535980.0,
 11535981.0,
 11535982.0,
 11535983.0,
 11535991.0,
 11536002.0,
 11536007.0,
 11536016.0,
 11536017.0,
 17827516.0,
 11536060.0,
 6252724.0,
 11536076.0,
 11536077.0,
 11536078.0,
 11536079.0,
 11536080.0,
 11536081.0,
 11536083.0,
 11536084.0,
 11536088.0,
 18757484.0,
 11536090.0,
 6252727.0,
 6252728.0,
 26216173.0,
 26216174.0,
 6252731.0,
 6252732.0,
 11536118.0,
 6252733.0,
 11536124.0,
 11536126.0,
 6252735.0,
 6252737.0,
 11536144.0,
 11536145.0,
 11536146.0,
 11536147.0,
 11536148.0,
 11536149.0,
 11536150.0,
 11536151.0,
 11536152.0,
 11536153.0,
 11536154.0,
 11536155.0,
 11536156.0,
 11536157.0,
 11536158.0,
 6252739.0,
 6252744.0,
 6252745.0,
 6252746.0,
 6252747.0,
 6252748.0,
 25167691.0,
 25167692.0,
 25167693.0,
 25167694.0,
 25167695.0,
 25167696.0,
 6252754.0,
 6252755.0,
 6252756.0,
 6252757.0,
 6252758.0,
 6252759.0,
 11536252.0,
 6252760.0,
 11536259.0,
 17797824.0,
 25167850.0,
 17827833.0,
 17827836.0,
 17827854.0,
 17827867.0,
 17827870.0,
 17827871.0,
 17827874.0,
 17827894.0,
 17827895.0,
 17827897.0,
 17827898.0,
 17827901.0,
 17827902.0,
 17827903.0,
 2501373.0,
 17827916.0,
 17827918.0,
 17827919.0,
 17827920.0,
 17827921.0,
 17827926.0,
 17827927.0,
 17827930.0,
 17827934.0,
 17827942.0,
 11536502.0,
 11536504.0,
 11536505.0,
 11536506.0,
 11536510.0,
 17827967.0,
 11536511.0,
 17827973.0,
 11536519.0,
 11536523.0,
 17827981.0,
 11536525.0,
 17827985.0,
 11536530.0,
 11536531.0,
 17827988.0,
 11536534.0,
 17827991.0,
 11536536.0,
 11536535.0,
 17827996.0,
 18757574.0,
 18757575.0,
 17828051.0,
 17828052.0,
 17828059.0,
 17828073.0,
 17828080.0,
 19925236.0,
 19925237.0,
 19925238.0,
 19925239.0,
 17828090.0,
 17828092.0,
 17828100.0,
 17828102.0,
 17828103.0,
 17828104.0,
 17828105.0,
 17828109.0,
 17828110.0,
 26216729.0,
 26216732.0,
 26216733.0,
 26216734.0,
 26216735.0,
 26216736.0,
 26216737.0,
 26216738.0,
 26216739.0,
 26216740.0,
 26216741.0,
 26216742.0,
 26216743.0,
 26216744.0,
 26216745.0,
 26216746.0,
 26216747.0,
 26216748.0,
 26216749.0,
 26216750.0,
 26216751.0,
 26216752.0,
 26216753.0,
 11536706.0,
 11536707.0,
 19925317.0,
 11536715.0,
 11536716.0,
 11536719.0,
 11536721.0,
 11536722.0,
 19925339.0,
 11536734.0,
 19925343.0,
 19925348.0,
 11536748.0,
 11536753.0,
 11536754.0,
 19925365.0,
 19925368.0,
 11536761.0,
 12712773.0,
 19925380.0,
 19925403.0,
 7342509.0,
 7342510.0,
 19925432.0,
 19925433.0,
 19925434.0,
 19925440.0,
 19925442.0,
 19925443.0,
 11536852.0,
 19925473.0,
 19925474.0,
 11536876.0,
 11536878.0,
 11536879.0,
 11536880.0,
 11536885.0,
 11536891.0,
 11536892.0,
 11536898.0,
 19925518.0,
 19925543.0,
 19925544.0,
 19925545.0,
 14682693.0,
 2099791.0,
 2099792.0,
 2099793.0,
 2099794.0,
 19925587.0,
 2099796.0,
 2099795.0,
 2099797.0,
 2099799.0,
 2099800.0,
 2099801.0,
 2099802.0,
 2099803.0,
 2099804.0,
 2099805.0,
 2099806.0,
 2099798.0,
 2099808.0,
 2099809.0,
 2099810.0,
 2099811.0,
 2099812.0,
 2099813.0,
 2099807.0,
 2099815.0,
 2099817.0,
 2099818.0,
 2099819.0,
 2099821.0,
 2099824.0,
 2099825.0,
 2099826.0,
 2099827.0,
 2099828.0,
 2099830.0,
 2099831.0,
 2099832.0,
 2099833.0,
 2099834.0,
 2099835.0,
 2099838.0,
 24119936.0,
 2099840.0,
 2099843.0,
 2099845.0,
 2099846.0,
 2099847.0,
 2099848.0,
 2099849.0,
 2099850.0,
 2099853.0,
 2099854.0,
 2099855.0,
 2099856.0,
 2099857.0,
 2099859.0,
 2099860.0,
 2099861.0,
 2099862.0,
 2099863.0,
 2099864.0,
 2099865.0,
 2099866.0,
 2099868.0,
 2099870.0,
 2099871.0,
 2099874.0,
 2099876.0,
 2099879.0,
 2099881.0,
 2099882.0,
 2099883.0,
 2099885.0,
 2099887.0,
 2099890.0,
 2099898.0,
 2099900.0,
 2099901.0,
 2099902.0,
 2099903.0,
 2099904.0,
 2099905.0,
 2099906.0,
 2099909.0,
 2099910.0,
 2099912.0,
 2099914.0,
 2099916.0,
 2099917.0,
 2099920.0,
 2099921.0,
 2099924.0,
 2099926.0,
 2099927.0,
 19925722.0,
 2099931.0,
 2099932.0,
 2099933.0,
 2099930.0,
 2099935.0,
 2099936.0,
 2099937.0,
 2099938.0,
 28553083.0,
 2099939.0,
 2099941.0,
 2099942.0,
 2099943.0,
 2099944.0,
 2099945.0,
 2099946.0,
 2099947.0,
 2099948.0,
 28553085.0,
 2099949.0,
 2099951.0,
 2099952.0,
 2099958.0,
 2099961.0,
 2099963.0,
 2099966.0,
 2099967.0,
 2099968.0,
 2099969.0,
 28553089.0,
 2099971.0,
 2099972.0,
 2099974.0,
 2099975.0,
 2099976.0,
 2099978.0,
 2099980.0,
 2099982.0,
 2099985.0,
 2099987.0,
 2099988.0,
 2099989.0,
 2099990.0,
 2099991.0,
 2099992.0,
 2099993.0,
 28553094.0,
 2099995.0,
 2099998.0,
 2100001.0,
 2100005.0,
 2100007.0,
 2100012.0,
 2100013.0,
 2100014.0,
 2100015.0,
 2100016.0,
 2100017.0,
 2100018.0,
 2100019.0,
 2100020.0,
 2100022.0,
 2100023.0,
 2100025.0,
 2100026.0,
 2100029.0,
 2100030.0,
 2100031.0,
 2100032.0,
 2100034.0,
 2100035.0,
 2100036.0,
 2100039.0,
 2100042.0,
 2100043.0,
 2100044.0,
 22509138.0,
 2100045.0,
 2100047.0,
 2100048.0,
 2100049.0,
 22509139.0,
 2100051.0,
 2100050.0,
 2100053.0,
 2100052.0,
 22509140.0,
 2100055.0,
 2100058.0,
 22509141.0,
 2100060.0,
 2100061.0,
 2100063.0,
 2100064.0,
 22509142.0,
 2100066.0,
 2100067.0,
 2100069.0,
 2100070.0,
 2100072.0,
 2100073.0,
 2100074.0,
 2100075.0,
 2100076.0,
 2100077.0,
 2100078.0,
 2100080.0,
 2100081.0,
 2100082.0,
 2100083.0,
 2100084.0,
 2100085.0,
 2100086.0,
 2100087.0,
 2100089.0,
 2100090.0,
 2100091.0,
 2100096.0,
 2100097.0,
 2100098.0,
 2100099.0,
 2100100.0,
 2100101.0,
 2100103.0,
 2100104.0,
 2100107.0,
 2100108.0,
 2100111.0,
 2100114.0,
 2100115.0,
 2100117.0,
 2100118.0,
 2100119.0,
 22023075.0,
 2100132.0,
 7343068.0,
 7343069.0,
 7343110.0,
 23287955.0,
 11537688.0,
 11537689.0,
 11537690.0,
 11537691.0,
 11537692.0,
 11537693.0,
 11537694.0,
 11537695.0,
 4585748.0,
 4585749.0,
 11537718.0,
 11537719.0,
 11537720.0,
 11537721.0,
 11537722.0,
 11537723.0,
 11537724.0,
 11537725.0,
 11537726.0,
 11537727.0,
 11537728.0,
 11537729.0,
 11537736.0,
 11537737.0,
 11537738.0,
 11537739.0,
 11537740.0,
 11537741.0,
 11537742.0,
 11537743.0,
 11537744.0,
 11537745.0,
 11537746.0,
 11537747.0,
 11537748.0,
 11537749.0,
 11537750.0,
 11537789.0,
 11537790.0,
 11537791.0,
 11537792.0,
 11537793.0,
 11537794.0,
 11537795.0,
 11537796.0,
 11537797.0,
 4585784.0,
 15630481.0,
 4585787.0,
 15630482.0,
 26218001.0,
 4585799.0,
 4585800.0,
 4585801.0,
 4585803.0,
 9440849.0,
 4585806.0,
 9440859.0,
 9440864.0,
 9440865.0,
 9440866.0,
 9440867.0,
 4585809.0,
 4585810.0,
 9440877.0,
 9440879.0,
 9440881.0,
 9440884.0,
 9440888.0,
 9440893.0,
 23287956.0,
 9440895.0,
 9440903.0,
 9440908.0,
 9440911.0,
 9440914.0,
 9440919.0,
 9440920.0,
 9440922.0,
 9440923.0,
 9440924.0,
 9440925.0,
 9440927.0,
 9440928.0,
 25169568.0,
 25169569.0,
 9440932.0,
 9440933.0,
 9440935.0,
 9440938.0,
 9440946.0,
 9440950.0,
 4585827.0,
 9440956.0,
 9440958.0,
 9440965.0,
 19926726.0,
 19926725.0,
 19926728.0,
 19926729.0,
 19926730.0,
 19926731.0,
 9440973.0,
 19926733.0,
 19926755.0,
 9441004.0,
 9441013.0,
 9441017.0,
 9441026.0,
 9441033.0,
 9441035.0,
 9441040.0,
 9441042.0,
 9441043.0,
 9441044.0,
 9441046.0,
 9441047.0,
 26218268.0,
 26218269.0,
 26218273.0,
 26218274.0,
 9441063.0,
 26218279.0,
 9441065.0,
 26218283.0,
 9441068.0,
 26218287.0,
 9441078.0,
 9441080.0,
 9441081.0,
 26218306.0,
 26218313.0,
 26218317.0,
 26218318.0,
 26218320.0,
 9441114.0,
 9441116.0,
 9441117.0,
 9441118.0,
 9441121.0,
 26218337.0,
 9441123.0,
 9441124.0,
 9441125.0,
 9441126.0,
 9441127.0,
 4585860.0,
 9441129.0,
 14892752.0,
 9441134.0,
 4585863.0,
 9441166.0,
 4585869.0,
 9441169.0,
 9441170.0,
 9441171.0,
 9441174.0,
 9441175.0,
 9441176.0,
 9441182.0,
 9441183.0,
 9441184.0,
 9441185.0,
 9441186.0,
 9441187.0,
 9441188.0,
 4585873.0,
 9441190.0,
 9441191.0,
 9441193.0,
 9441194.0,
 9441196.0,
 9441197.0,
 9441203.0,
 9441204.0,
 9441205.0,
 9441206.0,
 9441207.0,
 9441209.0,
 9441210.0,
 9441212.0,
 9441216.0,
 9441217.0,
 9441218.0,
 9441220.0,
 9441222.0,
 9441223.0,
 9441225.0,
 9441226.0,
 9441227.0,
 9441228.0,
 9441237.0,
 9441239.0,
 9441240.0,
 9441241.0,
 9441245.0,
 9441246.0,
 9441247.0,
 9441249.0,
 9441251.0,
 9441252.0,
 9441253.0,
 4585886.0,
 9441255.0,
 9441256.0,
 9441257.0,
 9441258.0,
 9441260.0,
 9441262.0,
 9441263.0,
 9441264.0,
 9441265.0,
 9441266.0,
 9441270.0,
 9441271.0,
 9441272.0,
 9441273.0,
 9441274.0,
 18798251.0,
 9441277.0,
 9441279.0,
 9441280.0,
 9441284.0,
 9441285.0,
 9441288.0,
 9441289.0,
 9441290.0,
 9441291.0,
 9441292.0,
 9441293.0,
 9441294.0,
 9441295.0,
 4585896.0,
 9441303.0,
 28301499.0,
 9441306.0,
 9441307.0,
 9441308.0,
 9441309.0,
 9441310.0,
 4585897.0,
 9441312.0,
 9441316.0,
 9441318.0,
 9441319.0,
 9441322.0,
 9441323.0,
 9441324.0,
 9441326.0,
 11504096.0,
 11504100.0,
 11504101.0,
 23287957.0,
 18878706.0,
 11538694.0,
 4585944.0,
 9441549.0,
 9441550.0,
 7344593.0,
 11504113.0,
 7295360.0,
 11504114.0,
 9441816.0,
 9441821.0,
 9441824.0,
 9441826.0,
 9441827.0,
 9441829.0,
 9441834.0,
 9441836.0,
 11504115.0,
 9441862.0,
 11504116.0,
 9441867.0,
 9441868.0,
 9441869.0,
 9441873.0,
 9441874.0,
 9441878.0,
 1053271.0,
 1053272.0,
 1053273.0,
 9441882.0,
 1053274.0,
 9441884.0,
 1053275.0,
 1053276.0,
 7295377.0,
 7295379.0,
 9441901.0,
 9441902.0,
 9441903.0,
 7295380.0,
 11539061.0,
 9441910.0,
 9441909.0,
 18879098.0,
 11880469.0,
 11504120.0,
 11880478.0,
 9442009.0,
 9442010.0,
 9442011.0,
 12922543.0,
 11880480.0,
 12922544.0,
 12922545.0,
 12922546.0,
 12922547.0,
 12922548.0,
 11880485.0,
 12922549.0,
 12922550.0,
 11880487.0,
 12922551.0,
 12922552.0,
 23073553.0,
 12922553.0,
 9442068.0,
 28316437.0,
 9442070.0,
 28316439.0,
 9442069.0,
 11880490.0,
 28316442.0,
 11880492.0,
 12922556.0,
 11880493.0,
 28316453.0,
 28316454.0,
 12922557.0,
 28316457.0,
 28316458.0,
 28316459.0,
 11880495.0,
 28316462.0,
 28316463.0,
 28316465.0,
 12922559.0,
 11880497.0,
 20976442.0,
 20976443.0,
 20976444.0,
 20976445.0,
 20976446.0,
 20976447.0,
 20976448.0,
 20976449.0,
 20976450.0,
 20976451.0,
 20976452.0,
 20976453.0,
 20976454.0,
 20976455.0,
 20976456.0,
 20976457.0,
 20976458.0,
 20976459.0,
 20976460.0,
 20976461.0,
 20976462.0,
 20976463.0,
 20976464.0,
 20976465.0,
 20976466.0,
 20976467.0,
 20976468.0,
 20976469.0,
 20976470.0,
 20976471.0,
 20976472.0,
 20976473.0,
 20976474.0,
 ...]

# RANK CROSS GRAPH CLIQUES

In [62]:
# Rank cnpj
path = "/dados01/workspace/ufmg_2021_m04/M04_final/M04-pipeline/fraud-detection-module/output/rank-cross-graph-quasi-cliques"

df_alarm_mcgqc = pd.read_csv(path, sep='\t', names=["cnpjs_weights", "items_weights", "alarm"])
df_alarm_mcgqc['items_weights'] = df_alarm_mcgqc['items_weights'].str.replace(',', ', ')

def remove_weights(cnpjs):
    cnpjs = cnpjs.split(',')
    new_cnpjs=[]
    for cnpj in cnpjs:
        index = cnpj.index('#')
        new_cnpjs.append(cnpj[0:index])
    return ', '.join(new_cnpjs)

cnpjs = df_alarm_mcgqc['cnpjs_weights']
cnpjs = cnpjs.apply(remove_weights)
df_alarm_mcgqc['cnpjs_weights'] = cnpjs


items = df_alarm_mcgqc['items_weights']
items = items.apply(remove_weights)
df_alarm_mcgqc['items_weights'] = items


df_alarm_mcgqc.rename(columns={'items_weights': 'items', 'cnpjs_weights': 'cnpjs'}, inplace=True)
df_alarm_mcgqc = df_alarm_mcgqc[['cnpjs',  'items',  'alarm']]

df_alarm_mcgqc = df_alarm_mcgqc.iloc[:-1]

In [63]:
df_alarm_mcgqc

,cnpjs,items,alarm
0,"14609448000111, 24897571000139","859919, 859920, 859921, 859922, 859923, 8...",2147483647
1,"1744153000106, 17192048000141","150423, 150428, 150429, 150437, 150439, 1...",2147483647
2,"2259625000106, 3470258000140","75218, 75219, 75222, 75228, 75236, 75274,...",2147483647
3,"22912480000108, 24897571000139","859919, 859920, 859921, 859922, 859923, 8...",2147483647
4,"22949891000160, 24897571000139","859919, 859920, 859921, 859922, 859923, 8...",2147483647
...,...,...,...
9665,"9943359000177, 22669693000142",4859301,0
9666,"994993000164, 10453283000180","11798651, 11798652, 11798653, 11798654, 11...",0
9667,"994993000164, 13281255000111","11798651, 11798652, 11798653, 11798654, 11...",0
9668,"994993000164, 3765702000154","11799904, 11799905, 11799906, 11799907, 11...",0
9669,"994993000164, 18784339000191","6673822, 6673823, 6673824, 6673825, 667382...",0

In [54]:
# Transformar coluna participations em uma lista
col_list = df_alarm_mcgqc['items'].to_list()

# transformar uma lista de string para uma lista de listas
b = []
for el in col_list:
    if el == "id_licitacao":
        continue
    b.append(eval(el))

# transformar lista de lista em uma unica lista
c = []
for sublist in b:
    if type(sublist) is int:
        c.append(sublist)
    else:
        for item in sublist:
            c.append(item)
itens_in_cross_graph_cliques = list(set(c))

# CRIAR DATAFRAME

In [55]:
itens = itens_in_participations + itens_in_cross_graph_cliques
itens = list(set(itens))

In [56]:
# Dataframe de itens com somentes itens em cnpj rank
df_itens =  part_df[part_df.id_item_licitacao.isin(itens)]
df_itens

,id_item_licitacao,id_licitacao,nome_item,nome_cidade,sigla_uf
473,34784,968,MACA,ACAIACA,MG
474,34785,968,TOMATES,ACAIACA,MG
475,34786,968,MELAO,ACAIACA,MG
476,34787,968,GOIABA,ACAIACA,MG
477,34788,968,CENOURA BAROA,ACAIACA,MG
...,...,...,...,...,...
13243202,28830716,880682,PRESTACAO DE SERVICOS DE TRANSPORTE EM GERAL C...,ESPERA FELIZ,MG
13243203,28830717,880682,"LOCACAO DE ESCAVADEIRA HIDRAULICA, CAPACIDADE ...",ESPERA FELIZ,MG
13243204,28830718,880682,"PRESTACAO DE SERVICOS DE RETROESCAVADEIRA, 4 X...",ESPERA FELIZ,MG
13243205,28830719,880682,"LOCACAO DE TRATOR, POTENCIA MINIMA DE 80 CAVAL...",ESPERA FELIZ,MG
13243206,28830720,880682,"CAMINHAO PRANCHA TRUCADO, PARA REALIZACAO DE T...",ESPERA FELIZ,MG

In [ ]:
# Save file
out_path = '/dados01/workspace/ufmg_2021_m04/apresentacao-dados/itens_reduced.csv'